#!/bin/bash
# Check root user access
if [ "$(id -u)" != 0 ]; then
  echo "Access denied. Run the script as 'root' user."
exit 1
fi

SHELL_WORKDIR="/opt/shellTaskEnv"
DEFAULT_LOGDIR="${SHELL_WORKDIR}/log"
DEFAULT_LOGDFILE="${DEFAULT_LOGDIR}/slellEnvAppService.log"
VENV="${SHELL_WORKDIR}/.venv"
export SHELL_WORKDIR

# CHECk LOGDIR
if [ ! -d "$DEFAULT_LOGDIR" ];
then
  mkdir -p $DEFAULT_LOGDIR
fi

# CHECk LOGFILE
if [ ! -f "$DEFAULT_LOGDFILE" ];
then
    touch $DEFAULT_LOGDFILE
fi
function logger(){
  echo "[$(date)][Info][$$]$1" |& tee -a $DEFAULT_LOGDFILE
}

logger "[Running...]"
# CHECk VIRTUAL_VENV
if [ ! -d "$VENV" ];
then
  python3 -m venv $VENV
fi

# ADD ENV File
source "${VENV}/bin/activate"
python3 "${SHELL_WORKDIR}/app/script/systemd/service/env.py"

# CHECK FILE
ENVFILE="${SHELL_WORKDIR}/app/script/systemd/service/.env"
if [ ! -f "$ENVFILE" ];
then
  logger "[Error][File $ENVFILE not found]"
  logger "[Error][Check the virtual environment of the 'env.py']"
  exit 1
fi
source $ENVFILE

# CHECK ENVIRON
if [ -z "$SHELL_LOGRATATION" ]; then
  logger "[Error][Virtual environment 'SHELL_LOGRATATION' not found]"
else
  logger "[Success][SHELL_LOGRATATION]"
fi
if [ -z "$SHELL_LOGRATATION_ARCH" ]; then
  logger "[Error][Virtual environment 'SHELL_LOGRATATION_ARCH' not found]"
else
  logger "[Success][SHELL_LOGRATATION_ARCH]"
fi
if [ -z "$SHELL_CONFPATH" ]; then
  logger "[Error][Virtual environment 'SHELL_CONFPATH' not found]"
else
  logger "[Success][SHELL_CONFPATH]"
fi
if [ -z "$SHELL_CONFDUMP" ]; then
  logger "[Error][Virtual environment'SHELL_CONFDUMP' not found]"
else
  logger "[Success][SHELL_CONFDUMP]"
fi

# CHMOD DIR
if [ -d "$SHELL_LOGRATATION" ];
then
  chmod -R 777 $SHELL_LOGRATATION
fi
if [ -d "$SHELL_LOGRATATION_ARCH" ];
then
  chmod -R 777 $SHELL_LOGRATATION_ARCH
fi
if [ -d "$SHELL_CONFPATH" ];
then
  chmod -R 777 $SHELL_CONFPATH
fi
if [ -d "$SHELL_CONFDUMP" ];
then
  chmod -R 777 $SHELL_CONFDUMP
fi

# RUN PYTHON MAIN
python3 /opt/shellTaskEnv/app/main.py
logger "[Stopping...]"